name: build client,server binaries
on:
  pull_request:
    paths:
      - "flake.nix"
      - "flake.lock"
      - "client/src/**"
      - "server/src/**"
  push:
    paths:
      - "flake.nix"
      - "flake.lock"
      - "client/src/**"
      - "server/src/**"
  workflow_dispatch:
permissions:
  contents: write
  id-token: write
jobs:
  build-all:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: release client
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            gh release create "${GITHUB_RUN_ID}-client" --draft=false --generate-notes
            gh release upload "${GITHUB_RUN_ID}-client" "flake.nix" --clobber
